controllers:
  resource: ../src/Controller/
  type: attribute

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_homepage:
  path: /
  controller: App\Controller\HomeController::home

target_path:
  path: /target-path
  controller: App\Controller\HomeController::home

admin_page:
  path: /admin
  controller: App\Controller\AdminController::index

app_mentions_legales:
  path: /mentions-legales
  controller: App\Controller\MentionsLegalesController::index

app_politiques_confidentialite:
  path: /politiques-confidentialite
  controller: App\Controller\PolitiquesConfidentialiteController::index
